/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_edu_pwr_pdabrowski_Splot2DInCPP */

#ifndef _Included_pl_edu_pwr_pdabrowski_Splot2DInCPP
#define _Included_pl_edu_pwr_pdabrowski_Splot2DInCPP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_edu_pwr_pdabrowski_Splot2DInCPP
 * Method:    calculate
 * Signature: ([[I[[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_pl_edu_pwr_pdabrowski_Splot2DInCPP_calculate
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
